version: '3'
services:
  alluxio-proxy:
    image: ${ALLUXIO_DOCKER_IMAGE_NAME}
    ports:
      - '39999:39999'
    hostname: ${ALLUXIO_WORKER_HOSTNAME}
    command: proxy
    environment:
      - ALLUXIO_PROXY_DEBUG=${ALLUXIO_PROXY_DEBUG}
      - ALLUXIO_MASTER_HOSTNAME=${ALLUXIO_MASTER_HOSTNAME}
    networks:
      - alluxio
  alluxio-worker:
    image: ${ALLUXIO_DOCKER_IMAGE_NAME}
    hostname: ${ALLUXIO_WORKER_HOSTNAME}
    shm_size: 5G
    command: worker
    ports:
      - '6606:6606'
      - '29998-30000:29998-30000'
    networks:
      - alluxio
    environment:
      - ALLUXIO_MASTER_HOSTNAME=${ALLUXIO_MASTER_HOSTNAME}
      - ALLUXIO_WORKER_HOSTNAME=${ALLUXIO_WORKER_HOSTNAME}
      - ALLUXIO_UNDERFS_ADDRESS=${ALLUXIO_UNDERFS_ADDRESS}
      - ALLUXIO_WORKER_MEMORY_SIZE=5GB
      - ALLUXIO_WORKER_DEBUG=${ALLUXIO_WORKER_DEBUG}
      - ALLUXIO_UNDERFS_OBJECT_STORE_MOUNT_SHARED_PUBLICLY=${ALLUXIO_UNDERFS_OBJECT_STORE_MOUNT_SHARED_PUBLICLY}

networks:
  alluxio:
