version: '3'
services:
  dat:
    hostname: stortest3.cadc.dao.nrc.ca
    image: at88mph/dat-registry
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    volumes:
      - '/var/local/dat-registry/data:/data'
