version: '3'
services:
  dat:
    image: at88mph/dat-clone
    ports:
      - '8080:8080'
      - '3282:3282'
    volumes:
      - '/var/local/dat/data:${DATA_DIR}:rw'
      - '/var/local/dat/config:/root/.dat:rw'
    network_mode: host
    environment:
      - DATA_DIR=${DATA_DIR}
      - DAT_KEY=${DAT_KEY}
      - DAT_REGISTRY_SERVER=${DAT_REGISTRY_SERVER}
      - DAT_LOGIN_EMAIL=${DAT_LOGIN_EMAIL}
      - DAT_LOGIN_PASSWORD=${DAT_LOGIN_PASSWORD}
